openapi: 3.1.0
info:
  title: Customer Management API
  description: REST APIs for managing customer data
  version: '1.0'
servers:
  - url: http://localhost:3002
    description: Local development environment

paths:
  /customers:
    get:
      operationId: fetchAllCustomers
      summary: Retrieve all customers
      description: Fetch a list of all customers
      responses:
        200:
          description: List of customers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        404:
          description: Customers not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Customer:
      type: object
      properties:
        customerId:
          type: string
          description: Unique identifier for the customer
        firstName:
          type: string
          description: First name of the customer
        lastName:
          type: string
          description: Last name of the customer
        email:
          type: string
          format: email
          description: Email address of the customer
        phone:
          type: string
          description: Phone number of the customer
        address:
          $ref: '#/components/schemas/Address'

    Address:
      type: object
      properties:
        street:
          type: string
          description: Street address
        city:
          type: string
          description: City of the address
        state:
          type: string
          description: State of the address
        zipCode:
          type: string
          description: Zip code of the address
        country:
          type: string
          description: Country of the address

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
